# Generated by Django 4.1.13 on 2025-05-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entriesdupa'},
        ),
    ]
